language: c++

services:
  - docker

before_install:
  - docker build -t raspberry-display .

script:
  - docker run -v $(pwd):/code raspberry-display:latest make
  - docker run -v $(pwd):/code raspberry-display:latest make install

